## Comparing training files
Martin Kircher provided two training_data files: one is human readable and the other one is one-hot-encoded.
Now we need to check that the information is actually in the same order.

In [1]:
import dask.dataframe as dd
import pandas as pd
import numpy as np
import sklearn
from sklearn.model_selection import ShuffleSplit

In [2]:
training = "/s/project/kipoi-cadd/data/raw/v1.3/training_data/training_data.tsv"
training_imputed = "/s/project/kipoi-cadd/data/raw/v1.3/training_data/training_data.imputed.csv"

training_dd = dd.read_csv(training, sep='\t', 
                          dtype={'PolyPhenVal': 'float64',
                                 'SIFTval': 'float64',
                                 'mirSVR-E': 'float64',
                                 'mirSVR-Score': 'float64',
                                 'relCDSpos': 'float64',
                                 'relProtPos': 'float64'})

training_imp_dd = dd.read_csv(training_imputed, assume_missing=True)
training_dd.head()

,y,Chrom,Pos,Ref,Alt,Type,Length,isTv,Consequence,GC,...,SIFTcat,SIFTval,mirSVR-Score.na,targetScan.na,cDNApos.na,CDSpos.na,protPos.na,Grantham.na,PolyPhenVal.na,SIFTval.na
0,0,1,379177,T,G,SNV,0,1,NC,0.48,...,UD,0.0,1,1,0,1,1,1,1,1
1,0,1,379274,C,G,SNV,0,1,NC,0.54,...,UD,0.0,1,1,0,1,1,1,1,1
2,0,1,379476,A,T,SNV,0,1,UP,0.63,...,UD,0.0,1,1,1,1,1,1,1,1
3,0,1,379631,C,G,SNV,0,1,UP,0.34,...,UD,0.0,1,1,1,1,1,1,1,1
4,0,1,379724,A,G,SNV,0,0,UP,0.28,...,UD,0.0,1,1,1,1,1,1,1,1

In [8]:
from dask_ml.model_selection import train_test_split
y = training_imp_dd.y
X = training_imp_dd.drop('y', axis=1)
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

lr = LogisticRegression(penalty='l2', solver='lbfgs', n_jobs=64)
lr.fit(X, y)
lr.predict(X)
lr.predict_proba(X)
lr.score(X, y)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8],
       [3, 4],
       [5, 6]])